branches:
  only:
    - feature/ODIN-424-appveyor

only_commits:
  message: /Release:/

image: macos

environment:
  nodejs_version: "12"

install:
  - npm install -g yarn
  - yarn install --frozen-lockfile
  - yarn prebuild:upload

test_script:
  - ls -alh
