branches:
  only:
    - master

#only_commits:
#  message: /chore\(release\):/

image: macos

environment:
  nodejs_version: "12"

install:
  - brew install openssl
  - export OPENSSL_ROOT_DIR=/usr/local/opt/openssl
  - npm install -g yarn
  - yarn install --frozen-lockfile
  - yarn prebuild:upload

test_script:
  - rm -rf ./*
  - git reset --hard
  - yarn install --frozen-lockfile
  - yarn test:ci
