branches:
  only:
    - master

only_commits:
  message: /chore\(release\):/

image: macos

environment:
  nodejs_version: "12"
  # same as RELEASE_JOB_UPLOAD_ARTIFACTS_TOKEN in github secrets, used to upload binaries to github releases
  GITHUB_TOKEN:
    secure: V9NUG3nW2iIL+WK5/HNHnhdGy1CZ6v4nbwjW79oaDAJ7GhaqU7faD026/JWlMaXI
  AWS_ACCESS_KEY_ID:
    secure: +i20g2Qtc2es30ynkLSoHP8mGkGKQebQNJgU9pj9RI0=
  AWS_SECRET_ACCESS_KEY:
    secure: n67mcRbzmDqHeUV52SXg9Aqz5pSHzEzQvhSa49TgtbXrFFuKi0Ee4xCSS5ugFcSX

install:
  - brew install openssl
  - export OPENSSL_ROOT_DIR=/usr/local/opt/openssl
  - npm install -g yarn
  - yarn install --frozen-lockfile
  - yarn prebuild:upload

test_script:
  - rm -rf ./*
  - git reset --hard
  - yarn install --frozen-lockfile
  - yarn test:ci
